In [ ]:
import re
import numpy as np
import pickle
import os

#1.THU THẬP DỮ LIỆU

#### Đọc dữ liệu từ folder.

In [ ]:
class FileData(object):
    def __init__(self, path):
        self.path = path
        with open(path, encoding='utf-16') as f:
          self.data = f.read()
          #print(self.data)

In [ ]:
ABSOLUTE_PATH = r"E:\Python\language\Train_Full"

In [ ]:
c_tri =  "\Chinh tri Xa hoi"

d_song = "\Doi song"

khoa_hoc = "\Khoa hoc"

kinh_doanh = "\Kinh doanh"

p_luat = "\Phap luat"

suc_khoe = "\Suc khoe"

the_gioi = "\The gioi"

the_thao = "\The thao"

van_hoa = "\Van hoa"

vi_tinh = "\Vi tinh"

In [ ]:
c_tri =  "/Chinh tri Xa hoi"

#d_song = "/Doi song"

khoa_hoc = "/Khoa hoc"

kinh_doanh = "/Kinh doanh"

p_luat = "/Phap luat"

suc_khoe = "/Suc khoe"

#the_gioi = "/The gioi"

the_thao = "/The thao"

#van_hoa = "/Van hoa"

#vi_tinh = "/Vi tinh"

In [ ]:
#corpus = [c_tri, d_song, khoa_hoc, kinh_doanh, p_luat, suc_khoe, the_gioi, the_thao, van_hoa, vi_tinh]

# Giam thieu du lieu
corpus = [c_tri, khoa_hoc, kinh_doanh, p_luat, suc_khoe, the_thao]

In [ ]:
for folder_path in range(len(corpus)):
    corpus[folder_path] = ABSOLUTE_PATH + corpus[folder_path]

In [ ]:
corpus[2]

'E:\\Python\\language\\Train_Full/Kinh doanh'

In [ ]:
import os
file_list = []
#count = 0

for folder_path in corpus:
    count = 0
    for name in os.listdir(folder_path):
        count +=1
        if count == 1500:
          break
        path = os.path.join(folder_path, name)
        if not os.path.isfile(path):
            continue
        file = FileData(path)
        file_list.append( file.data )
        # count +=1
        # if count == 5:
        #   break

In [ ]:
len(file_list)

8994

#### Lưu dữ liệu dưới dạng file pickle

In [ ]:
#path_corpus = "E:\Python\language\input_corpus.pkl"
path_corpus = 'E:\Python\language\input_cutdown_corpus.pkl'

with open(path_corpus, 'wb') as pickle_file:
    pickle.dump(file_list, pickle_file)

# 2.IMPORT Dữ liệu

In [ ]:
pk_path = '/home/phuong/Documents/2023_NLP/Code/PreData/input_cutdown_corpus.pkl'

#### Load dữ liệu đã được lưu trữ ở phần 1 ra sử dụng

In [ ]:
with open(pk_path, "rb") as f:
    data = pickle.load(f)

In [ ]:
len(data)

8994

In [ ]:
data[1]

' Xây dựng trạm dừng nghỉ cho xe đò\nTrên diện tích 10.000m2 sẽ xây dựng khu nhà ăn tự chọn phục vụ 400-500 người, khu siêu thị, trạm y tế, điện thoại công cộng, hai khu vực nhà vệ sinh, trạm xăng dầu... (ảnh mô hình). Dự kiến tổng kinh phí đầu tư khoảng 5 tỉ đồng, công trình sẽ thi công và đưa vào sử dụng trong năm 2005. \n\n'

### 2.1 TIEN XU LY

#### Xây dựng bộ ngữ liệu là 1 list chứa các câu. Thay thế dấu cách xuống dòng bằng dấu chấm cuối câu. Từ dấu chấm đó, tách văn bản theo các câu.

In [ ]:
import re
alphabet = '^[ _abcdefghijklmnopqrstuvwxyz0123456789áàảãạâấầẩẫậăắằẳẵặóòỏõọôốồổỗộơớờởỡợéèẻẽẹêếềểễệúùủũụưứừửữựíìỉĩịýỳỷỹỵđ!\"\',\-\.:;?_\(\)]+$'
def latin_extract(data):
    latin_extract_data=[]
    # duyet qua tung van ban
    for i in data:
      if i == 1:
        break
      # thay the xuong dong la dau cham ket thuc
      i=i.replace("\n",".")
      # tach van ban theo dau cham ket thuc
      sentences=i.split(".")
      # re.match(alphabet, j.lower()): kiểm tra xem phiên bản viết thường j có trong alphabet hay không.
      for j in sentences:
        if len(j.split()) > 2 and re.match(alphabet, j.lower()):
            latin_extract_data.append(j)

    return latin_extract_data

In [ ]:
training_data = latin_extract(data)

print(len(training_data))
training_data[10]

137028


' Từ 2-12: cấp giấy chứng nhận quyền sử dụng đất theo mẫu mới'

In [ ]:
# Hien thi de check

i = 100
while i < 110:
  print(training_data[i])
  i += 1

Đông đảo người dân đến vui chơi tại Thảo Cầm Viên - Ảnh: T
Các cổ động viên Bảo vệ thực vật Sài Gòn - Dofilm và nông nghiệp Sài Gòn Pakse đang chào đón cuộc đua - Ảnh: Nguyên Khôi 
Lễ mít tinh kỷ niệm 31 năm ngày giải phóng miền Nam, thống nhất đất nước, ngày Quốc tế Lao động 1-5 và chào mừng Đại hội X của Đảng thành công đã được tổ chức long trọng vào sáng 27-4
Ngày 28-4, Chương trình nghệ thuật đặc biệt "Cảm xúc tháng tư" do Sở VH-TT TP
HCM phối hợp với Đài truyền hình VN tổ chức tại công viên 30-4 thu hút đông đảo người dân đến xem
 Anh Nguyễn Hồng (Quận Bình Thạnh) chia sẻ "3 năm liền đều ra đây xem Cúp truyền hình rồi, chỉ để xem được mấy giây tay đua nào cán đích nhưng tôi đem sẵn cả nước, báo và ổ bánh mì ra đây"
Giữa dòng người, hai bạn trẻ Thùy, Hạnh vẫn thoăn thoắt giới thiệu sản phẩm và bán nước Trà xanh không độ
 "Hôm nay không khí đông vui quá, hàng bán chạy hẳn, ráng xong ngày hôm nay thôi, nhóm mình sẽ đi chơi vào ngày mai"
Peter và Anna đến từ Đan Mạch không ngừng chụp 

#### Liệt kê các từ, các kí tự gõ sai thường gặp trong tiếng Việt

In [ ]:
import numpy as np
from unidecode import unidecode

In [ ]:
letters=list("abcdefghijklmnopqrstuvwxyzáàảãạâấầẩẫậăắằẳẵặóòỏõọôốồổỗộơớờởỡợéèẻẽẹêếềểễệúùủũụưứừửữựíìỉĩịýỳỷỹỵđABCDEFGHIJKLMNOPQRSTUVWXYZÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÉÈẺẼẸÊẾỀỂỄỆÚÙỦŨỤƯỨỪỬỮỰÍÌỈĨỊÝỲỶỸỴĐ")
letters2=list("abcdefghijklmnopqrstuvwxyz")

typo={"ă":"aw","â":"aa","á":"as","à":"af","ả":"ar","ã":"ax","ạ":"aj","ắ":"aws","ổ":"oor","ỗ":"oox","ộ":"ooj","ơ":"ow",
"ằ":"awf","ẳ":"awr","ẵ":"awx","ặ":"awj","ó":"os","ò":"of","ỏ":"or","õ":"ox","ọ":"oj","ô":"oo","ố":"oos","ồ":"oof",
"ớ":"ows","ờ":"owf","ở":"owr","ỡ":"owx","ợ":"owj","é":"es","è":"ef","ẻ":"er","ẽ":"ex","ẹ":"ej","ê":"ee","ế":"ees","ề":"eef",
"ể":"eer","ễ":"eex","ệ":"eej","ú":"us","ù":"uf","ủ":"ur","ũ":"ux","ụ":"uj","ư":"uw","ứ":"uws","ừ":"uwf","ử":"uwr","ữ":"uwx",
"ự":"uwj","í":"is","ì":"if","ỉ":"ir","ị":"ij","ĩ":"ix","ý":"ys","ỳ":"yf","ỷ":"yr","ỵ":"yj","đ":"dd",
"Ă":"Aw","Â":"Aa","Á":"As","À":"Af","Ả":"Ar","Ã":"Ax","Ạ":"Aj","Ắ":"Aws","Ổ":"Oor","Ỗ":"Oox","Ộ":"Ooj","Ơ":"Ow",
"Ằ":"AWF","Ẳ":"Awr","Ẵ":"Awx","Ặ":"Awj","Ó":"Os","Ò":"Of","Ỏ":"Or","Õ":"Ox","Ọ":"Oj","Ô":"Oo","Ố":"Oos","Ồ":"Oof",
"Ớ":"Ows","Ờ":"Owf","Ở":"Owr","Ỡ":"Owx","Ợ":"Owj","É":"Es","È":"Ef","Ẻ":"Er","Ẽ":"Ex","Ẹ":"Ej","Ê":"Ee","Ế":"Ees","Ề":"Eef",
"Ể":"Eer","Ễ":"Eex","Ệ":"Eej","Ú":"Us","Ù":"Uf","Ủ":"Ur","Ũ":"Ux","Ụ":"Uj","Ư":"Uw","Ứ":"Uws","Ừ":"Uwf","Ử":"Uwr","Ữ":"Uwx",
"Ự":"Uwj","Í":"Is","Ì":"If","Ỉ":"Ir","Ị":"Ij","Ĩ":"Ix","Ý":"Ys","Ỳ":"Yf","Ỷ":"Yr","Ỵ":"Yj","Đ":"Dd"}

# dia phuong
region={"ẻ":"ẽ","ẽ":"ẻ","ũ":"ủ","ủ":"ũ","ã":"ả","ả":"ã","ỏ":"õ","õ":"ỏ","i":"j"}
region2={"s":"x","l":"n","n":"l","x":"s","d":"gi","S":"X","L":"N","N":"L","X":"S","Gi":"D","D":"Gi"}

# nguyen am
vowel=list("aeiouyáàảãạâấầẩẫậăắằẳẵặóòỏõọôốồổỗộơớờởỡợéèẻẽẹêếềểễệúùủũụưứừửữựíìỉĩịýỳỷỹỵ")

# viet tat
acronym={"không":"ko"," anh":" a","em":"e","biết":"bít","giờ":"h","gì":"j","muốn":"mún","học":"hok","yêu":"iu",
         "chồng":"ck","vợ":"vk"," ông":" ô","được":"đc","tôi":"t",
         "Không":"Ko"," Anh":" A","Em":"E","Biết":"Bít","Giờ":"H","Gì":"J","Muốn":"Mún","Học":"Hok","Yêu":"Iu",
         "Chồng":"Ck","Vợ":"Vk"," Ông":" Ô","Được":"Đc","Tôi":"T",}

# teencode
teen={"ch":"ck","ph":"f","th":"tk","nh":"nk",
      "Ch":"Ck","Ph":"F","Th":"Tk","Nh":"Nk"}

### Hàm gây nhiễu, giả lập teencode

In [ ]:
# function for adding mistake( noise)
def teen_code(sentence,pivot):
    random = np.random.uniform(0,1,1)[0]
    new_sentence=str(sentence)
    if random>pivot:
        for word in acronym.keys():
            if re.search(word, new_sentence):
                random2 = np.random.uniform(0,1,1)[0]
                if random2 <0.5:
                    new_sentence=new_sentence.replace(word,acronym[word])
        for word in teen.keys():
            if re.search(word, new_sentence):
                random3 = np.random.uniform(0,1,1)[0]
                if random3 <0.05:
                    new_sentence=new_sentence.replace(word,teen[word])
        return new_sentence
    else:
        return sentence


def add_noise(sentence, pivot1,pivot2):
    sentence=teen_code(sentence,0.5)
    noisy_sentence = ""
    i = 0
    while i < len(sentence):
        if sentence[i] not in letters:
            noisy_sentence+=sentence[i]
        else:
            random = np.random.uniform(0,1,1)[0]
            if random < pivot1:
                noisy_sentence+=(sentence[i])
            elif random<pivot2:
                if sentence[i] in typo.keys() and sentence[i] in region.keys():
                    random2=np.random.uniform(0,1,1)[0]
                    if random2<=0.4:
                        noisy_sentence+=typo[sentence[i]]
                    elif random2<0.8:
                        noisy_sentence+=region[sentence[i]]
                    elif random2<0.95 :
                        noisy_sentence+=unidecode(sentence[i])
                    else:
                        noisy_sentence+=sentence[i]
                elif sentence[i] in typo.keys():
                    random3=np.random.uniform(0,1,1)[0]
                    if random3<=0.6:
                        noisy_sentence+=typo[sentence[i]]
                    elif random3<0.9 :
                        noisy_sentence+=unidecode(sentence[i])
                    else:
                        noisy_sentence+=sentence[i]
                elif sentence[i] in region.keys():
                    random4=np.random.uniform(0,1,1)[0]
                    if random4<=0.6:
                        noisy_sentence+=region[sentence[i]]
                    elif random4<0.85 :
                        noisy_sentence+=unidecode(sentence[i])
                    else:
                        noisy_sentence+=sentence[i]
                elif i<len(sentence)-1 :
                    if sentence[i] in region2.keys() and (i==0 or sentence[i-1] not in letters) and sentence[i+1] in vowel:
                        random5=np.random.uniform(0,1,1)[0]
                        if random5<=0.9:
                            noisy_sentence+=region2[sentence[i]]
                        else:
                            noisy_sentence+=sentence[i]
                    else:
                        noisy_sentence+=sentence[i]

            else:
                new_random = np.random.uniform(0,1,1)[0]
                if new_random <=0.33:
                    if i == (len(sentence) - 1):
                        continue
                    else:
                        noisy_sentence+=(sentence[i+1])
                        noisy_sentence+=(sentence[i])
                        i += 1
                elif new_random <= 0.66:
                    random_letter = np.random.choice(letters2, 1)[0]
                    noisy_sentence+=random_letter
                else:
                    pass

        i += 1
    return noisy_sentence

#### Thử nghiệm hàm add_noise lần lượt với các tham số của pivot1, pivot2

In [ ]:
print(add_noise('Làm sạch văn bản, tách các cụm từ trong câu, nếu có kí tự đặc biệt thì xóa chúng đi',0.94,0.985))
print(add_noise('Làm sạch văn bản, tách các cụm từ trong câu, nếu có kí tự đặc biệt thì xóa chúng đi',0.85,0.88))
print(add_noise('Làm sạch văn bản, tách các cụm từ trong câu, nếu có kí tự đặc biệt thì xóa chúng đi',0.8,0.9))

Làm sạch văn bản, tách các cụm từ trong câu, nếu có kí tự đặc bjệt thì xóa chúng đi
Làm sach văn bản, tách các cụm tw trog câu, nế uc k ítự đgc biệt tì xóa chúng đi
Làm sich văn bản, tách các cụm ừt trno gnâu, nếp có kí to đặc biệt thì xóa chúng iđ


#### Làm sạch văn bản, tách các cụm từ trong câu, nếu có kí tự đặc biệt thì xóa chúng đi


In [ ]:
import itertools

\w: Đây là một ký tự thay thế có ý nghĩa trong regex, đại diện cho bất kỳ ký tự chữ cái (bao gồm cả chữ cái viết hoa và chữ cái viết thường) hoặc số. Nó không bao gồm ký tự không phải chữ cái hoặc số.

[\w ]+: Đoạn này tương ứng với một hoặc nhiều ký tự chữ cái (bao gồm cả dấu cách) hoặc số. Dấu cách ở đây cho phép xuất hiện trong cụm từ.

r'...': Chuỗi được xác định bởi r trước dấu nháy đơn là một raw string, có nghĩa là các dấu gạch chéo không được xử lý đặc biệt. Điều này thường được sử dụng trong các biểu thức chính quy để tránh việc xử lý đặc biệt của các ký tự như \.

findall: Phương thức này của đối tượng regex được sử dụng để tìm tất cả các chuỗi con trong văn bản đầu vào mà khớp với biểu thức chính quy. Trong trường hợp này, nó trả về danh sách các cụm từ trong văn bản.
Hàm trả về một danh sách các cụm từ trong văn bản, trong đó mỗi cụm từ được định nghĩa bắt đầu từ một ký tự chữ cái hoặc số và có thể chứa cả dấu cách.

In [ ]:
def extract_phrases(text):
    return re.findall(r'\w[\w ]+', text)

In [ ]:
def _extract_phrases(data):
    phrases = itertools.chain.from_iterable(extract_phrases(text) for text in data)
    phrases = [p.strip() for p in phrases if len(p.split()) > 1]

    return phrases

In [ ]:
phrases = _extract_phrases(training_data)

print(len(phrases))
print(phrases[10])

334297
2 triệu con gia cầm của 12 huyện thị


#### Chia tập ngữ điệu thành 2-gram. Từng phần tử trong list gồm có 2 từ.

In [ ]:
from nltk import ngrams
from tqdm import tqdm

In [ ]:
# Một từ tiếng Việt không có quá 7 kí tự, một bigram lúc này không quá 15 kí tự
NGRAM = 2
MAXLEN = 40

Với giá trị MAXLEN=40, hàm sẽ giữ lại các bi-grams có độ dài (tính bằng số ký tự) không vượt quá 40. Các bi-grams dài hơn 40 sẽ bị loại bỏ khỏi danh sách list gram.

In [ ]:
def gen_ngrams(words, n=2):
    return ngrams(words.split(), n)

def generate_bi_grams(phrases):
    list_ngrams = []
    for p in tqdm(phrases):

      # neu khong nam trong alphabet thi bo qua
      if not re.match(alphabet, p.lower()):
        continue

      # tach p thanh cac bi gram
      for ngr in gen_ngrams(p, NGRAM):
        if len(" ".join(ngr)) < MAXLEN:
          list_ngrams.append(" ".join(ngr))

    return list_ngrams

In [ ]:
list_ngrams = generate_bi_grams(phrases)

  0%|          | 0/334297 [00:00<?, ?it/s]

100%|██████████| 334297/334297 [00:01<00:00, 218458.93it/s]


In [ ]:
print(len(list_ngrams))
print(list_ngrams[7])

2981627
triệu gia


In [ ]:
alphabet = ['\x00', ' ', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'á', 'à', 'ả', 'ã', 'ạ', 'â', 'ấ', 'ầ', 'ẩ', 'ẫ', 'ậ', 'ă', 'ắ', 'ằ', 'ẳ', 'ẵ', 'ặ', 'ó', 'ò', 'ỏ', 'õ', 'ọ', 'ô', 'ố', 'ồ', 'ổ', 'ỗ', 'ộ', 'ơ', 'ớ', 'ờ', 'ở', 'ỡ', 'ợ', 'é', 'è', 'ẻ', 'ẽ', 'ẹ', 'ê', 'ế', 'ề', 'ể', 'ễ', 'ệ', 'ú', 'ù', 'ủ', 'ũ', 'ụ', 'ư', 'ứ', 'ừ', 'ử', 'ữ', 'ự', 'í', 'ì', 'ỉ', 'ĩ', 'ị', 'ý', 'ỳ', 'ỷ', 'ỹ', 'ỵ', 'đ', 'Á', 'À', 'Ả', 'Ã', 'Ạ', 'Â', 'Ấ', 'Ầ', 'Ẩ', 'Ẫ', 'Ậ', 'Ă', 'Ắ', 'Ằ', 'Ẳ', 'Ẵ', 'Ặ', 'Ó', 'Ò', 'Ỏ', 'Õ', 'Ọ', 'Ô', 'Ố', 'Ồ', 'Ổ', 'Ỗ', 'Ộ', 'Ơ', 'Ớ', 'Ờ', 'Ở', 'Ỡ', 'Ợ', 'É', 'È', 'Ẻ', 'Ẽ', 'Ẹ', 'Ê', 'Ế', 'Ề', 'Ể', 'Ễ', 'Ệ', 'Ú', 'Ù', 'Ủ', 'Ũ', 'Ụ', 'Ư', 'Ứ', 'Ừ', 'Ử', 'Ữ', 'Ự', 'Í', 'Ì', 'Ỉ', 'Ĩ', 'Ị', 'Ý', 'Ỳ', 'Ỷ', 'Ỹ', 'Ỵ', 'Đ']
print(alphabet)
print(len(alphabet))

['\x00', ' ', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'á', 'à', 'ả', 'ã', 'ạ', 'â', 'ấ', 'ầ', 'ẩ', 'ẫ', 'ậ', 'ă', 'ắ', 'ằ', 'ẳ', 'ẵ', 'ặ', 'ó', 'ò', 'ỏ', 'õ', 'ọ', 'ô', 'ố', 'ồ', 'ổ', 'ỗ', 'ộ', 'ơ', 'ớ', 'ờ', 'ở', 'ỡ', 'ợ', 'é', 'è', 'ẻ', 'ẽ', 'ẹ', 'ê', 'ế', 'ề', 'ể', 'ễ', 'ệ', 'ú', 'ù', 'ủ', 'ũ', 'ụ', 'ư', 'ứ', 'ừ', 'ử', 'ữ', 'ự', 'í', 'ì', 'ỉ', 'ĩ', 'ị', 'ý', 'ỳ', 'ỷ', 'ỹ', 'ỵ', 'đ', 'Á', 'À', 'Ả', 'Ã', 'Ạ', 'Â', 'Ấ', 'Ầ', 'Ẩ', 'Ẫ', 'Ậ', 'Ă', 'Ắ', 'Ằ', 'Ẳ', 'Ẵ', 'Ặ', 'Ó', 'Ò', 'Ỏ', 'Õ', 'Ọ', 'Ô', 'Ố', 'Ồ', 'Ổ', 'Ỗ', 'Ộ', 'Ơ', 'Ớ', 'Ờ', 'Ở', 'Ỡ', 'Ợ', 'É', 'È', 'Ẻ', 'Ẽ', 'Ẹ', 'Ê', 'Ế', 'Ề', 'Ể', 'Ễ', 'Ệ', 'Ú', 'Ù', 'Ủ', 'Ũ', 'Ụ', 'Ư', 'Ứ', 'Ừ', 'Ử', 'Ữ', 'Ự', 'Í', 'Ì', 'Ỉ', 'Ĩ', 'Ị', 'Ý', 'Ỳ', 'Ỷ', 'Ỹ', 'Ỵ', 'Đ']
1

#3. Xây dựng mô hình

In [ ]:
# Build the neural network
# this is adapted from the seq2seq architecture, which can be used for Machine Translation, Text Summarization Image Captioning ...
from keras.models import Sequential
from keras.layers import Activation, TimeDistributed, Dense,LSTM, Bidirectional
from keras.callbacks import Callback, ModelCheckpoint
from tensorflow.keras.optimizers import Adam # - Works

2023-12-07 09:12:27.996293: I tensorflow/core/util/port.cc:111] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-12-07 09:12:27.998449: I tensorflow/tsl/cuda/cudart_stub.cc:28] Could not find cuda drivers on your machine, GPU will not be used.
2023-12-07 09:12:28.026942: E tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:9342] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2023-12-07 09:12:28.027016: E tensorflow/compiler/xla/stream_executor/cuda/cuda_fft.cc:609] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2023-12-07 09:12:28.027043: E tensorflow/compiler/xla/stream_executor/cuda/cuda_blas.cc:1518] Unable to register cuBLAS factory: Attempting to regi

In [ ]:
MAXLEN

40

In [ ]:
len(alphabet)

199

In [ ]:
encoder = LSTM(256,input_shape=(MAXLEN, len(alphabet)), return_sequences=True)

In [ ]:
decoder=Bidirectional(LSTM(256, return_sequences=True, dropout=0.2))

In [ ]:
model=Sequential()
model.add(encoder)
model.add(decoder)
model.add(TimeDistributed(Dense(256)))
model.add(Activation('relu'))
model.add(TimeDistributed(Dense(len(alphabet))))
model.add(Activation('softmax'))

Sử dụng mô hình Sequential.\
là một lớp trong Keras cho phép bạn tạo ra một mô hình học máy tuần tự bằng cách thêm các layers một cách tuần tự.\
tạo ra một layer LSTM với 256 units, sử dụng dữ liệu đầu vào có độ dài tối đa là MAXLEN và số lượng features tại mỗi time step là len(alphabet). \
tạo ra một layer LSTM bidirectional với 256 units, và được áp dụng kỹ thuật dropout để kiểm soát quá mức và làm cho mô hình tổng quát hóa tốt hơn. \
TimeDistributed(Dense(256)):
+ Dense(256): Là một tầng mạng nơ-ron đầy đủ kết nối (fully connected layer) với 256 đơn vị (neurons) hoặc nút. Tầng này kết nối mỗi đầu vào từ tầng trước nó với mỗi đầu ra của nó.
+ TimeDistributed(): Được sử dụng khi muốn áp dụng tầng mạng nơ-ron cho mỗi "thời điểm" của dữ liệu đầu vào.\

Activation('relu') là một hàm kích hoạt được sử dụng trong các mô hình mạng nơ-ron, và ở đây, 'relu' là viết tắt của Rectified Linear Unit. Hàm kích hoạt này thường được áp dụng sau một tầng mạng nơ-ron để giúp mô hình học được các đặc trưng phi tuyến tính và tăng cường khả năng học của nó.
+ Ưu điểm của ReLU: không có giới hạn dưới, điều này có thể giúp mô hình học được các đặc trưng phức tạp và biểu diễn chúng một cách hiệu quả. So với các hàm kích hoạt khác như sigmoid hoặc tanh, ReLU không đòi hỏi nhiều tính toán, điều này giúp tăng tốc quá trình huấn luyện mô hình.
+ Hạn chế: khi các đơn vị ReLU có thể trở thành 0 với đầu vào âm và không thể hồi phục lại, làm cho chúng không thể tham gia vào quá trình học.

Activation('softmax'): Hàm softmax chuyển đầu ra của một tầng mạng nơ-ron thành một phân phối xác suất, tức là tạo ra một tập hợp các giá trị có tổng bằng 1, giúp mô hình có thể dự đoán lớp của mỗi mẫu dữ liệu.




In [ ]:
model.compile(loss='categorical_crossentropy',
              optimizer=Adam(lr=0.001),
              metrics=['accuracy'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 40, 256)           466944    
                                                                 
 bidirectional (Bidirection  (None, 40, 512)           1050624   
 al)                                                             
                                                                 
 time_distributed (TimeDist  (None, 40, 256)           131328    
 ributed)                                                        
                                                                 
 activation (Activation)     (None, 40, 256)           0         
                                                                 
 time_distributed_1 (TimeDi  (None, 40, 199)           51143     
 stributed)                                                      
                                                        

Chỉ số tốc độ học được sử dụng trong đề tài này là learning rate của hàm Adam, tham số này quyết định đến mức độ nhanh hay chậm của quá trình hội tụ. Nếu tốc độ học quá lớn khiến mô hình bỏ qua các điểm tối ưu cục bộ, dẫn đến kết quả cho ra kém. Nếu tốc độ học quá chậm dẫn đến mô hình hội tụ chậm, tốn thời gian đào tạo. Giá trị lr = 0.001 trong đề tài được đặt theo mặc định.\
Tham số loss='categorical_crossentropy' được sử dụng để chỉ định hàm mất mát cho một mô hình phân loại đa lớp. Hàm mất mát này được tính bằng cách so sánh các xác suất dự đoán của mô hình với các nhãn thực tế.

In [ ]:
from tensorflow.keras.utils import plot_model
plot_model(model, to_file='model.png')

You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) for plot_model to work.


#### Tách data

In [ ]:
from sklearn.model_selection import train_test_split
train_data, valid_data = train_test_split(list_ngrams, test_size=0.2, random_state=42)

In [ ]:
len(list_ngrams)
list_ngrams[7]

'triệu gia'

In [ ]:
print(len(list_ngrams))
print(len(train_data))
print(len(valid_data))
print(train_data[1])

2981627
2385301
596326
thuyền có


#### Mã hóa câu thành ma trận 2 chiều và giải mã câu đó

In [ ]:
# Padding hai đầu đoạn văn bản để tất cả bigram có độ dài bằng nhau
def encoder_data(text, maxlen=MAXLEN):
        #print("Maxlen", maxlen)
        text = "\x00" + text
        #print("text", text)
        x = np.zeros((maxlen, len(alphabet)))
        #print("X ban dau", x)
        for i, c in enumerate(text[:maxlen]):
            x[i, alphabet.index(c)] = 1
        if i < maxlen - 1:
          for j in range(i+1, maxlen):
            x[j, 0] = 1
        return x

def decoder_data(x):
    x = x.argmax(axis=-1)
    #print("x hien tai", x)
    dem = ''.join(alphabet[i] for i in x)
    #print("Do dai cau van", len(dem))

    return dem

#### Qúa trình embedding một đoạn văn bản và trả về ma trận x của văn bản.

In [ ]:
print(encoder_data("Tôi tên là LÊ TUẤN").shape)
print(encoder_data("Tôi tên là LÊ TUẤN"))

(40, 199)
[[1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [ ]:
# Cần phải sử dụng data-generation vì dataset quá lớn để fit với memory
BATCH_SIZE = 512
def generate_data(data, batch_size):
    cur_index = 0
    while True:
        x, y = [], []
        for i in range(batch_size):
            y.append(encoder_data(data[cur_index]))
            x.append(encoder_data(add_noise(data[cur_index],0.94,0.985)))
            cur_index += 1
            if cur_index > len(data)-1:
                cur_index = 0
        yield np.array(x), np.array(y)

BATCH_SIZE là kích thước của mỗi batch dữ liệu được sử dụng trong quá trình huấn luyện. Việc sử dụng generator và một kích thước batch nhỏ giúp đảm bảo tính linh hoạt và hiệu suất trong quá trình đào tạo mô hình.

In [ ]:
import os
train_generator = generate_data(train_data, batch_size=BATCH_SIZE)
validation_generator = generate_data(valid_data, batch_size=BATCH_SIZE)
#This is a Wikipedia-based image-text dataset for Vietnamese. It's extracted from Google WIT (https://github.com/google-research.../wit/blob/main/DATA.md). It contains raw images from Wikipedia (over 200 GBs). It can be used for image captioning, image-text retrieval, ...
#https://huggingface.co/datasets/dinhanhx/google-wit-vie=BATCH_SIZE)

In [ ]:
for i in range(5):  # Generate 5 batches for demonstration
    batch_x, batch_y = next(train_generator)
    print("Batch X shape:", batch_x)
    print("Batch Y shape:", batch_y)

Batch X shape: [[[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0

In [ ]:
# train the model and save to the Model folder
checkpointer = ModelCheckpoint(filepath='/home/phuong/Documents/2023_NLP/Code/Model/my_model_weight.h5', save_best_only=True, verbose=1)

train_generator: Đối tượng generator cho dữ liệu huấn luyện. Generator là một cách hiệu quả để xử lý và đưa dữ liệu vào mô hình dần dần thay vì nạp toàn bộ dữ liệu vào bộ nhớ.\
steps_per_epoch: Số bước (steps) mỗi epoch. Một bước là một lần cập nhật trọng số của mô hình dựa trên một lô dữ liệu. len(train_data)//BATCH_SIZE tính toán số bước cần thiết để duyệt qua toàn bộ dữ liệu đào tạo.\
epochs: Số lần duyệt qua toàn bộ dữ liệu đào tạo. Ở đây, mô hình sẽ được đào tạo qua dữ liệu đào tạo 5 lần.\
validation_data: Đối tượng generator cho dữ liệu validation. Dữ liệu này được sử dụng để đánh giá hiệu suất của mô hình sau mỗi epoch.\
validation_steps: Số bước (steps) cho dữ liệu validation. Tương tự như steps_per_epoch, được tính toán từ len(valid_data)//BATCH_SIZE.\
callbacks: Danh sách các callback được sử dụng trong quá trình huấn luyện. Ở đây, checkpointer có thể là một callback để lưu trọng số của mô hình khi có sự cải thiện trên dữ liệu validation.\

In [ ]:
model.fit( train_generator, steps_per_epoch=len(train_data)//BATCH_SIZE, epochs=5,
                    validation_data=validation_generator, validation_steps=len(valid_data)//BATCH_SIZE,
                    callbacks=[checkpointer] )

Epoch 1/5
4658/4658 [==============================] - ETA: 0s - loss: 0.1030 - accuracy: 0.9782
Epoch 1: val_loss improved from inf to 0.02529, saving model to /home/phuong/Documents/2023_NLP/Code/Model/my_model_weight.h5
4658/4658 [==============================] - 5512s 1s/step - loss: 0.1030 - accuracy: 0.9782 - val_loss: 0.0253 - val_accuracy: 0.9940
Epoch 2/5


/home/phuong/anaconda3/lib/python3.11/site-packages/keras/src/engine/training.py:3079: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


4658/4658 [==============================] - ETA: 0s - loss: 0.0225 - accuracy: 0.9946
Epoch 2: val_loss improved from 0.02529 to 0.01831, saving model to /home/phuong/Documents/2023_NLP/Code/Model/my_model_weight.h5
4658/4658 [==============================] - 6245s 1s/step - loss: 0.0225 - accuracy: 0.9946 - val_loss: 0.0183 - val_accuracy: 0.9955
Epoch 3/5
4658/4658 [==============================] - ETA: 0s - loss: 0.0176 - accuracy: 0.9956
Epoch 3: val_loss improved from 0.01831 to 0.01600, saving model to /home/phuong/Documents/2023_NLP/Code/Model/my_model_weight.h5
4658/4658 [==============================] - 6282s 1s/step - loss: 0.0176 - accuracy: 0.9956 - val_loss: 0.0160 - val_accuracy: 0.9960
Epoch 4/5
4658/4658 [==============================] - ETA: 0s - loss: 0.0155 - accuracy: 0.9961
Epoch 4: val_loss improved from 0.01600 to 0.01427, saving model to /home/phuong/Documents/2023_NLP/Code/Model/my_model_weight.h5
4658/4658 [==============================] - 6273s 1s/step 

#5.DỰ ĐOÁN

In [ ]:
from collections import Counter
from keras.models import load_model
from nltk.tokenize import word_tokenize
from nltk import ngrams,word_tokenize
import numpy as np
import re
import unidecode
import string
from tqdm import tqdm

In [ ]:
#model = load_model('E:\Python\language\spell_0.99.h5')
model = load_model('/home/phuong/Documents/2023_NLP/Code/Model/my_model_weight.h5')
model.make_predict_function()

In [ ]:
NGRAM=2
MAXLEN=40 # INPUT SHAPE
alphabet = ['\x00', ' ', '_', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'á', 'à', 'ả', 'ã', 'ạ', 'â', 'ấ', 'ầ', 'ẩ', 'ẫ', 'ậ', 'ă', 'ắ', 'ằ', 'ẳ', 'ẵ', 'ặ', 'ó', 'ò', 'ỏ', 'õ', 'ọ', 'ô', 'ố', 'ồ', 'ổ', 'ỗ', 'ộ', 'ơ', 'ớ', 'ờ', 'ở', 'ỡ', 'ợ', 'é', 'è', 'ẻ', 'ẽ', 'ẹ', 'ê', 'ế', 'ề', 'ể', 'ễ', 'ệ', 'ú', 'ù', 'ủ', 'ũ', 'ụ', 'ư', 'ứ', 'ừ', 'ử', 'ữ', 'ự', 'í', 'ì', 'ỉ', 'ĩ', 'ị', 'ý', 'ỳ', 'ỷ', 'ỹ', 'ỵ', 'đ', 'Á', 'À', 'Ả', 'Ã', 'Ạ', 'Â', 'Ấ', 'Ầ', 'Ẩ', 'Ẫ', 'Ậ', 'Ă', 'Ắ', 'Ằ', 'Ẳ', 'Ẵ', 'Ặ', 'Ó', 'Ò', 'Ỏ', 'Õ', 'Ọ', 'Ô', 'Ố', 'Ồ', 'Ổ', 'Ỗ', 'Ộ', 'Ơ', 'Ớ', 'Ờ', 'Ở', 'Ỡ', 'Ợ', 'É', 'È', 'Ẻ', 'Ẽ', 'Ẹ', 'Ê', 'Ế', 'Ề', 'Ể', 'Ễ', 'Ệ', 'Ú', 'Ù', 'Ủ', 'Ũ', 'Ụ', 'Ư', 'Ứ', 'Ừ', 'Ử', 'Ữ', 'Ự', 'Í', 'Ì', 'Ỉ', 'Ĩ', 'Ị', 'Ý', 'Ỳ', 'Ỷ', 'Ỹ', 'Ỵ', 'Đ']
letters=list("abcdefghijklmnopqrstuvwxyzáàảãạâấầẩẫậăắằẳẵặóòỏõọôốồổỗộơớờởỡợéèẻẽẹêếềểễệúùủũụưứừửữựíìỉĩịýỳỷỹỵđABCDEFGHIJKLMNOPQRSTUVWXYZÁÀẢÃẠÂẤẦẨẪẬĂẮẰẲẴẶÓÒỎÕỌÔỐỒỔỖỘƠỚỜỞỠỢÉÈẺẼẸÊẾỀỂỄỆÚÙỦŨỤƯỨỪỬỮỰÍÌỈĨỊÝỲỶỸỴĐ")
accepted_char=list((string.digits + ''.join(letters)))

In [ ]:
def call(sentence):
    def extract_phrases(text):
        pattern = r'\w[\w ]*|\s\W+|\W+'
        return re.findall(pattern, text)

    def encoder_data(text, maxlen=MAXLEN):
            text = "\x00" + text
            x = np.zeros((maxlen, len(alphabet)))
            for i, c in enumerate(text[:maxlen]):
                x[i, alphabet.index(c)] = 1
            if i < maxlen - 1:
              for j in range(i+1, maxlen):
                x[j, 0] = 1
            return x

    def decoder_data(x):
        x = x.argmax(axis=-1)
        return ''.join(alphabet[i] for i in x)

    def nltk_ngrams(words, n=2):
        return ngrams(words.split(), n)

    def guess(ngram):
        text = ' '.join(ngram)
        preds = model.predict(np.array([encoder_data(text)]), verbose=0)
        return decoder_data(preds[0]).strip('\x00')

    def correct(sentence):
        for i in sentence:
            if i not in accepted_char:
                sentence=sentence.replace(i," ")
        ngrams = list(nltk_ngrams(sentence, n=NGRAM))
        guessed_ngrams = list(guess(ngram) for ngram in ngrams)

        print("N gram", ngrams)
        print("guess", guessed_ngrams)

        #return guessed_ngrams

        candidates = [Counter() for _ in range(len(guessed_ngrams) + NGRAM - 1)]
        for nid, ngram in (enumerate(guessed_ngrams)):
            for wid, word in (enumerate(re.split(' +', ngram))):
                candidates[nid + wid].update([word])

        # for c in candidates:
        #     print(c.most_common(1))
        output = ' '.join(c.most_common(1)[0][0] for c in candidates)
        return output

    guess = correct(sentence)

    return guess

In [ ]:
#sentence = "Các phát thank viên dẫn cương trink"
#sentence = "Hom lay tooi đi hoc"
#sentence ='Tôi yêu thích họk ngôn ngữ mớj'
#sentence = 'Thnh pố Hồ Chí Mình là mộp địa điểm du lịch nổi tiếg'
sentence = 'Các phát thank viên, ngưowfi dẫn chương trìnk đeu là cac chuyeen gja sử dụng ngôn ngữ. Thế nkưng đa phần họ ềđu cho rằng mìnk ko có khiếu ăn nosi từ nkỏ, vậy tạo sao hoj vẫn thafnh công nkờ vào tài ăn nói của mìnk? Nguyên nkân rất đơn giản, đó là vì họ tự nkận thấy mìnk nói năng ko tốt, nên luôn cố gắng để nâng cao kĩ năng giao tiế'
guess = call(sentence)
print(guess)

N gram [('Các', 'phát'), ('phát', 'thank'), ('thank', 'viên'), ('viên', 'ngưowfi'), ('ngưowfi', 'dẫn'), ('dẫn', 'chương'), ('chương', 'trìnk'), ('trìnk', 'đeu'), ('đeu', 'là'), ('là', 'cac'), ('cac', 'chuyeen'), ('chuyeen', 'gja'), ('gja', 'sử'), ('sử', 'dụng'), ('dụng', 'ngôn'), ('ngôn', 'ngữ'), ('ngữ', 'Thế'), ('Thế', 'nkưng'), ('nkưng', 'đa'), ('đa', 'phần'), ('phần', 'họ'), ('họ', 'ềđu'), ('ềđu', 'cho'), ('cho', 'rằng'), ('rằng', 'mìnk'), ('mìnk', 'ko'), ('ko', 'có'), ('có', 'khiếu'), ('khiếu', 'ăn'), ('ăn', 'nosi'), ('nosi', 'từ'), ('từ', 'nkỏ'), ('nkỏ', 'vậy'), ('vậy', 'tạo'), ('tạo', 'sao'), ('sao', 'hoj'), ('hoj', 'vẫn'), ('vẫn', 'thafnh'), ('thafnh', 'công'), ('công', 'nkờ'), ('nkờ', 'vào'), ('vào', 'tài'), ('tài', 'ăn'), ('ăn', 'nói'), ('nói', 'của'), ('của', 'mìnk'), ('mìnk', 'Nguyên'), ('Nguyên', 'nkân'), ('nkân', 'rất'), ('rất', 'đơn'), ('đơn', 'giản'), ('giản', 'đó'), ('đó', 'là'), ('là', 'vì'), ('vì', 'họ'), ('họ', 'tự'), ('tự', 'nkận'), ('nkận', 'thấy'), ('thấy', 'mìnk'

In [ ]:
import pickle
with open('/home/phuong/Documents/2023_NLP/Code/PreData/test_corpus.pkl', "rb") as f:
    data = pickle.load(f)

In [ ]:
len(data)

8994